### ISSUE TITLE
Compatibility with simapp on cometbtf 0.38.5

### ISSUE THREAD

**Issue by cxyzhang0** [iqlusioninc/tmkms#860]
Is the latest tmkms compatible with CometBFT 0.38.5? I am getting the following CONSENSUS FAILURE on simd node. On my other nodes with CometBFT 0.37.1, tmkms works fine.

`
3:39PM INF Timed out dur=4988.977 height=1 module=consensus round=0 step=RoundStepNewHeight
3:39PM DBG received tock height=1 module=consensus round=0 step=RoundStepNewHeight timeout=4988.977
3:39PM DBG entering new round height=1 module=consensus previous=1/0/RoundStepNewHeight proposer=091D81F4226ED6CF45EBC752C1F6DA5B905D727F round=0
3:39PM DBG entering propose step current=1/0/RoundStepNewRound height=1 module=consensus round=0
3:39PM DBG node is a validator height=1 module=consensus round=0
3:39PM DBG propose step; our turn to propose height=1 module=consensus proposer=091D81F4226ED6CF45EBC752C1F6DA5B905D727F round=0
3:39PM DBG Received tick module=consensus new_ti={"duration":3000000000,"height":1,"round":0,"step":3} old_ti={"duration":4988977000,"height":1,"round":0,"step":1}
3:39PM DBG Timer already stopped module=consensus
3:39PM DBG Scheduled timeout dur=3000 height=1 module=consensus round=0 step=RoundStepPropose
3:39PM DBG signed proposal height=1 module=consensus proposal="Proposal{1/0 (6B07C091A05D6A6E89F0C155135E25BD64CBDAFAC4EEF13B243606589B63CED9:1:57D0BFFBDAEE, -1) 4E9E852CD78E @ 2024-02-25T23:39:20.504474Z}" round=0
3:39PM DBG Broadcast channel=32 module=p2p
3:39PM INF received proposal module=consensus proposal="Proposal{1/0 (6B07C091A05D6A6E89F0C155135E25BD64CBDAFAC4EEF13B243606589B63CED9:1:57D0BFFBDAEE, -1) 4E9E852CD78E @ 2024-02-25T23:39:20.504474Z}" proposer=091D81F4226ED6CF45EBC752C1F6DA5B905D727F
3:39PM INF received complete proposal block hash=6B07C091A05D6A6E89F0C155135E25BD64CBDAFAC4EEF13B243606589B63CED9 height=1 module=consensus
3:39PM DBG entering prevote step current=1/0/RoundStepPropose height=1 module=consensus round=0
3:39PM DBG prevote step: ProposalBlock is valid height=1 module=consensus round=0
3:39PM DBG signed and pushed vote height=1 module=consensus round=0 vote="Vote{0:091D81F4226E 1/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 6B07C091A05D 94AE5BE4FC19 000000000000 @ 2024-02-25T23:39:20.518948Z}"
3:39PM DBG Broadcast channel=32 module=p2p
3:39PM DBG Attempt to update stats for non-existent peer module=consensus peer=
3:39PM DBG adding vote cs_height=1 extLen=0 extSigLen=0 module=consensus val_index=0 vote_height=1 vote_type=SIGNED_MSG_TYPE_PREVOTE
3:39PM DBG Broadcast channel=32 module=p2p
3:39PM DBG added vote to prevote module=consensus prevotes="VoteSet{H:1 R:0 T:SIGNED_MSG_TYPE_PREVOTE +2/3:6B07C091A05D6A6E89F0C155135E25BD64CBDAFAC4EEF13B243606589B63CED9:1:57D0BFFBDAEE(1) BA{1:x} map[]}" vote="Vote{0:091D81F4226E 1/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 6B07C091A05D 94AE5BE4FC19 000000000000 @ 2024-02-25T23:39:20.518948Z}"
3:39PM DBG updating valid block because of POL module=consensus pol_round=0 valid_round=-1
3:39PM DBG Broadcast channel=32 module=p2p
3:39PM DBG entering precommit step current=1/0/RoundStepPrevote height=1 module=consensus round=0
3:39PM DBG precommit step; +2/3 prevoted proposal block; locking hash=6B07C091A05D6A6E89F0C155135E25BD64CBDAFAC4EEF13B243606589B63CED9 height=1 module=consensus round=0
3:39PM DBG Broadcast channel=32 module=p2p
3:39PM ERR CONSENSUS FAILURE!!! err="non-recoverable error when signing vote (1/0)" module=consensus stack="goroutine 129 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x44\npanic({0x1032bfe60?, 0x14000dd42a0?})\n\truntime/panic.go:770 +0x124\ngithub.com/cometbft/cometbft/consensus.(*State).signVote(0x1400117ea88, 0x2, {0x140020d5b40, 0x20, 0x20}, {0xd9e76c?, {0x140020d43c0?, 0x1400426f27c?, 0x160?}}, 0x140003e9a40)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2388 +0x4e4\ngithub.com/cometbft/cometbft/consensus.(*State).signAddVote(0x1400117ea88, 0x2, {0x140020d5b40, 0x20, 0x20}, {0x7?, {0x140020d43c0?, 0x0?, 0x0?}}, 0x140003e9a40)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2439 +0x1a4\ngithub.com/cometbft/cometbft/consensus.(*State).enterPrecommit(0x1400117ea88, 0x1, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:1536 +0x1058\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0x1400117ea88, 0x14001034820, {0x0, 0x0})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2296 +0x14a4\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0x1400117ea88, 0x14001034820, {0x0?, 0x10059d610?})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x28\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0x1400117ea88, {{0x1038cc2e0, 0x14001716a08}, {0x0, 0x0}})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x300\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0x1400117ea88, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:855 +0x370\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 1\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0xf0\n"
3:39PM INF service stop impl=baseWAL module=consensus msg="Stopping baseWAL service" wal=testnet/chain-5/data/cs.wal/wal
3:39PM INF service stop impl=Group module=consensus msg="Stopping Group service" wal=testnet/chain-5/data/cs.wal/wal

`

**Comment by cxyzhang0** [comment]
It is apparently being addressed per https://github.com/iqlusioninc/tmkms/pull/857. So I am closing this one.
